
Grape.create!([
  {name: "Frontenac", short_des: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ", long_des: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. ", pic: "Aglianico_del_Vulture_new.jpg", regions: "Rome", publish: true, supply: "person5", share: "7", like: "8"},
  {name: "Frontenac blanc", short_des: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ", long_des: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,", pic: "amarone_300x300.jpg", regions: "Milano", publish: true, supply: "person2", share: "6", like: "7"},
  {name: "Frontenac gris", short_des: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ", long_des: "Vigorous and very disease resistant. Wine has a characteristic peach flavor. Can be high in acidity.Vigorous and very disease resistant. Wine has a characteristic peach flavor. Can be high in acidity.Vigorous and very disease resistant. Wine has a characteristic peach flavor. Can be high in acidity.", pic: "Albarola_new.jpg", regions: "Rondon", publish: true, supply: "1", share: "4", like: "5"},
  {name: "La Crescent", short_des: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ", long_des: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. ", pic: "Avana_new.jpg", regions: "italy", publish: true, supply: "Person1", share: "3", like: "4"}
])
Wine.create!([
  {name: "Fruit of the Month Club", short_des: "Fruit of the Month Club", long_des: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. ", pic: "download-2.jpg", regions: "rome", wine: "Red wine", publish: true, share: "5", like: "6"},
  {name: "Beer of the Month Club", short_des: "Beer of the Month Club", long_des: "Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,", pic: "download-1.jpg", regions: "paris", wine: "white wine", publish: true, share: "3", like: "2"}
])
Category.create!([
  {name: "Red"},
  {name: "White"},
  {name: "Bubbly"},
  {name: "Rose"},
  {name: "Desert"},
  {name: "Places"}
])
Company.create!([
  {name: "Four Seasons Hotel San Francisco", category: 3, subcategory: nil, city: "San Francisco", share: 11, like: 39, lat: 37.786134, lng: -122.4043034, photo: "https://maps.googleapis.com/maps/api/place/photo?maxheight=400&photoreference=CoQBdwAAADdGfQb1pmgcMLZD6s89vWbz-ylO7WVeYpmQGM8UIocDD8aMJI1eYjxpNITjMf3P7alUhskBXts6biqw0uNjMr91U89W-J0Pf7VEKyva9egkVSgUPgzDTgl88C_AM6M9lcEPa7FcuN5xzsoIlm-Lp1SvBioAh6uFgEe-ln-_DyFjEhDBKk7xhK-V5v6oF07C_scuGhTPeEiQCUMrHrCaYHBPQanr5NNgwg&key=AIzaSyD_mMKLGBULdpg7KvEFfdoHQpdbu83EG-Q", address: "757 Market St, San Francisco, CA 94103, United States"},
  {name: "Palace Hotel Luxury Collection Hotel San Francisco", category: 3, subcategory: nil, city: "San Francisco", share: 4, like: 8, lat: 37.779044, lng: -122.418757, photo: "place-image.png", address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102"},
  {name: "San Francisco Marriott Marquis Union Square", category: 3, subcategory: nil, city: "San Francisco", share: 2, like: 1, lat: 37.779044, lng: -122.418757, photo: "place-image.png", address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102"},
  {name: "The Westin St Francis San Francisco On Union Square", category: 3, subcategory: nil, city: "San Francisco", share: 2, like: 1, lat: 37.779044, lng: -122.418757, photo: "place-image.png", address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102"},
  {name: "CABERNET SAUVIGNON", category: 1, subcategory: nil, city: "San Francisco", share: 89, like: 2, lat: 37.779044, lng: -122.418757, photo: "place-image.png", address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102"},
  {name: "Sutter Home Cabernet Sauvignon  187ML Mini bottle ", category: 1, subcategory: nil, city: "San Francisco", share: 18, like: 1, lat: 37.779044, lng: -122.418757, photo: "place-image.png", address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102"},
  {name: "Ruffino Chianti Riserva Ducale Gold Label 2012  750ML ", category: 1, subcategory: nil, city: "San Francisco", share: 9, like: 2, lat: 37.7616766, lng: -122.4199847, photo: "https://maps.googleapis.com/maps/api/place/photo?maxheight=400&photoreference=CoQBdwAAAMhWnInWvcGUVVmDMpfCJdow8u5mUbJxdnQ9OaDyf-1YowkF5ILTANDRUu6DI7B2zkCX6UaTTxYq0vE-5eGrPArQI-Gi4MxODV0DQVvkQ0ET_ip5Zui-e3C7ibUQfvkbcje9ouDDF7v0Za0bKqAItJ4T9OhlPHZD7ih8gMDfkJH8EhCzsH3OhfnMRktfO8BUxFjMGhTEaT5uKWYrvo1xNSufxZHwAOIgJA&key=AIzaSyD_mMKLGBULdpg7KvEFfdoHQpdbu83EG-Q", address: "3417 18th St, San Francisco, CA 94110, United States"},
  {name: "Porta Vita Rosso  1.50L ", category: 1, subcategory: nil, city: "San Francisco", share: 5, like: 2, lat: 37.779044, lng: -122.418757, photo: "place-image.png", address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102"},
  {name: "Americas Travel", category: 4, subcategory: nil, city: "San Francisco", share: nil, like: nil, lat: 37.779044, lng: -122.418757, photo: "place-image.png", address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102"},
  {name: "World Expeditions", category: 4, subcategory: nil, city: "San Francisco", share: nil, like: nil, lat: 32.753203, lng: -117.186474, photo: "place-image.png", address: "4312 Witherby St, San Diego, CA 92103, United States"},
  {name: "Europe Travel On Any Budget!", category: 4, subcategory: nil, city: "San Francisco", share: 2, like: 1, lat: 37.779044, lng: -122.418757, photo: "place-image.png", address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102"},
  {name: "Travel Visa Pro", category: 4, subcategory: nil, city: "San Francisco", share: nil, like: nil, lat: 37.779044, lng: -122.418757, photo: "place-image.png", address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102"},
  {name: "Fashion Community Week", category: 2, subcategory: nil, city: "San Francisco", share: 35, like: 1, lat: 37.779044, lng: -122.418757, photo: "place-image.png", address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102"},
  {name: "Macy’s Front Row", category: 2, subcategory: nil, city: "San Francisco", share: 9, like: 4, lat: 37.779044, lng: -122.418757, photo: "place-image.png", address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102"},
  {name: "Benicia Fashion Runway Weekend", category: 2, subcategory: nil, city: "San Francisco", share: 1, like: 1, lat: 37.779044, lng: -122.418757, photo: "place-image.png", address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102"},
  {name: "Fashion Art Santa Cruz", category: 2, subcategory: nil, city: "San Francisco", share: 1, like: 1, lat: 37.779044, lng: -122.418757, photo: "place-image.png", address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102"},
  {name: "Toronado", category: 5, subcategory: nil, city: "San Francisco", share: 5, like: 4, lat: 37.771878, lng: -122.4312124, photo: "https://maps.googleapis.com/maps/api/place/photo?maxheight=400&photoreference=CoQBdwAAAL4fQu0M1XqafM057eV79q-78PzrHrtaoOuoINqUdo_76g5yleWFfjtKFN5AZNQTshkysY9-eIdBDV_u2uMce76Gkrq-ImEfzwk6UBP9jYjb6SdUjZPBAmXsSrvQqcIxnowq1AuvZtLvfr-J8TeByMvpVcF6PRMCLAnEFjhpoalJEhAVdYCEP4eVbk6hkId1ZcsAGhTA_QmSnQVBrN6thcMLwQFGYjbGeA&key=AIzaSyD_mMKLGBULdpg7KvEFfdoHQpdbu83EG-Q", address: "547 Haight St, San Francisco, CA 94117, United States"},
  {name: "Mikkeller Bar", category: 5, subcategory: nil, city: "San Francisco", share: 4, like: 4, lat: 37.7839519, lng: -122.4090592, photo: "https://maps.googleapis.com/maps/api/place/photo?maxheight=400&photoreference=CoQBdwAAALuBIk6Z0fn-cecR3AD6ZNEUvhz7wXBzeSt0XhuEkI_XgNhpf05ITcRQ6ObgtWLL1cuMb8uYE869HgVfDJhs60yaq4vtK6xKDTZ4b-sUyu1IWfRZPLOv20RS36AZKxu0NnfvOwZz_FaY6WQrDn7j-RVS-j00KBo8F8bND6d1FY0MEhD34AUHUz6D-e4_Tgb4tdc6GhQQesRn5lgFOYJSJv47bLIfOmw_PA&key=AIzaSyD_mMKLGBULdpg7KvEFfdoHQpdbu83EG-Q", address: "34 Mason St, San Francisco, CA 94102, United States"},
  {name: "Liquid Gold", category: 5, subcategory: nil, city: "San Francisco", share: 2, like: 1, lat: 37.779044, lng: -122.418757, photo: "place-image.png", address: "1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102"},
  {name: "Hopwater Distribution", category: 5, subcategory: nil, city: "San Francisco", share: 1, like: 1, lat: 37.7900311, lng: -122.4113436, photo: "https://maps.googleapis.com/maps/api/place/photo?maxheight=400&photoreference=CoQBdwAAAJOaFNFeZ8LFGVhUgE5eQmxbGVXsvtJwdOybYqD2JatP-xPtmyIeBQciobEWD-3ZxQYu6WK7zyBmniiNKyOcDo2-fFFmcYlnGAczZnkCccX0ncEaOva5-T082eMXOg9WkFBtLC8Y-En697W0oJ9Sosl9AKEkXXDKjhWHtmw0MB7zEhCTcSIkVZLn_64c2m6r0bsDGhSjtZytPxo3WpSUipGTHAVkncFS-w&key=AIzaSyD_mMKLGBULdpg7KvEFfdoHQpdbu83EG-Q", address: "850 Bush St, San Francisco, CA 94108, United States"}
])
Ip.create!([
  {address: nil, company_id: 17, share: 1, like: nil},
  {address: nil, company_id: 17, share: 1, like: nil},
  {address: nil, company_id: 17, share: nil, like: 1},
  {address: nil, company_id: 18, share: 1, like: nil},
  {address: nil, company_id: 18, share: nil, like: 1},
  {address: nil, company_id: 17, share: 1, like: nil},
  {address: nil, company_id: 18, share: 1, like: nil},
  {address: nil, company_id: 18, share: 1, like: nil},
  {address: nil, company_id: 18, share: nil, like: 1},
  {address: nil, company_id: 17, share: nil, like: 1},
  {address: nil, company_id: 19, share: 1, like: nil},
  {address: nil, company_id: 17, share: 1, like: nil},
  {address: nil, company_id: 14, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 7, share: 1, like: nil},
  {address: nil, company_id: 8, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 7, share: 1, like: nil},
  {address: nil, company_id: 8, share: 1, like: nil},
  {address: nil, company_id: 8, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 7, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 7, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 7, share: 1, like: nil},
  {address: nil, company_id: 7, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 7, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 6, share: 1, like: nil},
  {address: nil, company_id: 7, share: 1, like: nil},
  {address: nil, company_id: 8, share: 1, like: nil},
  {address: nil, company_id: 2, share: 1, like: nil},
  {address: nil, company_id: 1, share: 1, like: nil},
  {address: nil, company_id: 4, share: 1, like: nil},
  {address: nil, company_id: 1, share: 1, like: nil},
  {address: nil, company_id: 3, share: 1, like: nil},
  {address: nil, company_id: 1, share: 1, like: nil},
  {address: nil, company_id: 2, share: 1, like: nil},
  {address: nil, company_id: 13, share: nil, like: 1},
  {address: nil, company_id: 14, share: nil, like: 1},
  {address: nil, company_id: 14, share: nil, like: 1},
  {address: nil, company_id: 14, share: nil, like: 1},
  {address: nil, company_id: 15, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 14, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 14, share: 1, like: nil},
  {address: nil, company_id: 14, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 14, share: 1, like: nil},
  {address: nil, company_id: 14, share: 1, like: nil},
  {address: nil, company_id: 14, share: 1, like: nil},
  {address: nil, company_id: 14, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 16, share: 1, like: nil},
  {address: nil, company_id: 16, share: nil, like: 1},
  {address: nil, company_id: 15, share: nil, like: 1},
  {address: nil, company_id: 14, share: nil, like: 1},
  {address: nil, company_id: 14, share: 1, like: nil},
  {address: nil, company_id: 13, share: 1, like: nil},
  {address: nil, company_id: 5, share: 1, like: nil},
  {address: nil, company_id: 7, share: nil, like: 1},
  {address: nil, company_id: 8, share: nil, like: 1},
  {address: nil, company_id: 11, share: 1, like: nil},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 2, share: nil, like: 1},
  {address: nil, company_id: 2, share: nil, like: 1},
  {address: nil, company_id: 1, share: 1, like: nil},
  {address: nil, company_id: 2, share: nil, like: 1},
  {address: nil, company_id: 2, share: nil, like: 1},
  {address: nil, company_id: 2, share: nil, like: 1},
  {address: nil, company_id: 2, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: 1, like: nil},
  {address: nil, company_id: 1, share: 1, like: nil},
  {address: nil, company_id: 1, share: 1, like: nil},
  {address: nil, company_id: 1, share: 1, like: nil},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: 1, like: nil},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1},
  {address: nil, company_id: 1, share: nil, like: 1}
])
SubCategory.create!([
  {name: "Sub Brunch Place 6", category_id: 1},
  {name: "Sub Brunch Place 7", category_id: 1},
  {name: "Sub Brunch Place 8", category_id: 1},
  {name: "Sub Fashion Events 6", category_id: 2},
  {name: "Sub Fashion Events 7", category_id: 2},
  {name: "Sub Fashion Events 8", category_id: 2},
  {name: "Sub Hotel 6", category_id: 3},
  {name: "Sub Hotel 7", category_id: 3},
  {name: "Sub Hotel 8", category_id: 3},
  {name: "Sub Travel Agency 6", category_id: 4},
  {name: "Sub Travel Agency 7", category_id: 4},
  {name: "Sub Travel Agency 8", category_id: 4},
  {name: "Sub Craft Breweire 6", category_id: 5},
  {name: "Sub Craft Breweire 7", category_id: 5},
  {name: "Sub Craft Breweire 8", category_id: 5},
  {name: "Italian Restaurants", category_id: 6}
])
